"use client";

import { useI18n } from "@/lib/i18n/context";
import ShareButton from "./ShareButton";
import QRCodeShare from "./QRCodeShare";
import CountdownTimerWrapper from "./CountdownTimerWrapper";
import { getCourtDisplay } from "@/lib/utils/getCourtDisplay";
import Link from "next/link";
import MarkdownText from "./MarkdownText";

interface SportsPageClientProps {
  singleEvent: any;
  hasStarted: boolean;
  tournamentStartDate: Date;
  matchesToShow: any[];
  hasUpcomingToday: boolean;
  latestAnnouncement?: any;
}

export default function SportsPageClient({
  singleEvent,
  hasStarted,
  tournamentStartDate,
  matchesToShow,
  hasUpcomingToday,
  latestAnnouncement,
}: SportsPageClientProps) {
  const { t, locale } = useI18n();

  const title = hasUpcomingToday ? t('sports.todaySchedule') : t('sports.tomorrowSchedule');
  const emptyMessage = hasUpcomingToday ? t('sports.noMatchesToday') : t('sports.noMatchesTomorrow');

  return (
    <>
      {/* Header Section */}
      <div className="text-center mb-8 sm:mb-12 animate-fadeIn">
        <div className="flex flex-col items-center justify-center gap-3 sm:gap-4 mb-4 sm:mb-6">
          <h1 className="text-3xl sm:text-4xl lg:text-5xl font-bold text-ntu-green px-4 leading-tight">
            {singleEvent?.name || "NTU Tennis – 114 Freshman Cup"}
          </h1>
        </div>
        <div className="flex flex-col sm:flex-row items-center justify-center gap-3 mt-4 sm:mt-6 px-4">
          <ShareButton title={singleEvent?.name || "NTU Tennis 賽事"} className="w-full sm:w-auto" />
          <QRCodeShare className="w-full sm:w-auto" />
        </div>
      </div>

      {/* Tournament Overview */}
      {singleEvent && (
        <div className="bg-white rounded-xl shadow-lg p-6 sm:p-8 mb-6 sm:mb-8 border border-gray-100 animate-scaleIn hover:shadow-xl transition-shadow duration-300">
          <h2 className="text-xl sm:text-2xl font-semibold text-ntu-green mb-4 sm:mb-6">{t('sports.tournamentOverview')}</h2>
          <div className="space-y-3 sm:space-y-4 text-gray-700">
            <div className="flex flex-col sm:flex-row items-start sm:items-center gap-1 sm:gap-0">
              <span className="font-semibold text-gray-800 min-w-[80px] sm:min-w-[100px] text-sm sm:text-base">{t('sports.dates')}：</span>
              <span className="text-sm sm:text-base">
                {new Date(singleEvent.start_date).toLocaleDateString(locale === 'zh' ? 'zh-TW' : 'en-US')} - {new Date(singleEvent.end_date).toLocaleDateString(locale === 'zh' ? 'zh-TW' : 'en-US')}
              </span>
            </div>
            <div className="flex flex-col sm:flex-row items-start sm:items-center gap-1 sm:gap-0">
              <span className="font-semibold text-gray-800 min-w-[80px] sm:min-w-[100px] text-sm sm:text-base">{t('sports.venue')}：</span>
              <span className="text-sm sm:text-base">{singleEvent.venue}</span>
            </div>
            {singleEvent.description && (
              <div className="flex flex-col sm:flex-row items-start gap-1 sm:gap-0">
                <span className="font-semibold text-gray-800 min-w-[80px] sm:min-w-[100px] text-sm sm:text-base">{t('sports.description')}：</span>
                <span className="text-sm sm:text-base">{singleEvent.description}</span>
              </div>
            )}
          </div>
        </div>
      )}

      {/* Purpose Statement */}
      {singleEvent?.description && (
        <div className="bg-white rounded-xl shadow-lg p-6 sm:p-8 mb-6 sm:mb-8 border border-gray-100 animate-scaleIn hover:shadow-xl transition-shadow duration-300">
          <h2 className="text-xl sm:text-2xl font-semibold text-ntu-green mb-4 sm:mb-6">{t('sports.eventDescription')}</h2>
          <p className="text-gray-700 leading-relaxed whitespace-pre-wrap text-sm sm:text-base">
            {singleEvent.description}
          </p>
        </div>
      )}

      {/* Countdown Timer (only before start) */}
      {!hasStarted && (
        <div className="bg-gradient-to-br from-white to-green-50 rounded-xl shadow-lg p-6 sm:p-8 mb-6 sm:mb-8 border border-gray-100 animate-scaleIn">
          <h2 className="text-xl sm:text-2xl font-semibold text-ntu-green mb-4 sm:mb-6 text-center">
            {t('sports.timeUntilStart')}
          </h2>
          <CountdownTimerWrapper targetDate={tournamentStartDate} />
        </div>
      )}

      {/* Today's or Tomorrow's Matches */}
      {matchesToShow.length > 0 && (
        <div className="bg-gradient-to-r from-yellow-50 to-amber-50 border-l-4 border-yellow-400 p-4 sm:p-6 mb-6 sm:mb-8 rounded-xl shadow-md animate-scaleIn">
          <div className="flex flex-col sm:flex-row sm:items-start sm:justify-between mb-3 sm:mb-4 gap-2">
            <h2 className="text-base sm:text-lg font-semibold text-yellow-800">{title}</h2>
            <span className="text-xs sm:text-sm text-yellow-700">{t('sports.autoGenerated')}</span>
          </div>
          
          {/* Desktop Table View */}
          <div className="hidden md:block overflow-x-auto -mx-2">
            <table className="min-w-full divide-y divide-yellow-200">
              <thead>
                <tr className="bg-yellow-100">
                  <th className="px-4 py-3 text-left text-xs font-medium text-yellow-800 uppercase tracking-wider">{t('sports.time')}</th>
                  <th className="px-4 py-3 text-left text-xs font-medium text-yellow-800 uppercase tracking-wider">{t('sports.court')}</th>
                  <th className="px-4 py-3 text-left text-xs font-medium text-yellow-800 uppercase tracking-wider">{t('sports.matchup')}</th>
                  <th className="px-4 py-3 text-center text-xs font-medium text-yellow-800 uppercase tracking-wider">{t('sports.status')}</th>
                </tr>
              </thead>
              <tbody className="bg-white divide-y divide-yellow-200">
                {matchesToShow.map((m: any) => {
                  const timeStr = new Intl.DateTimeFormat(locale === 'zh' ? "zh-TW" : "en-US", {
                    hour: "2-digit",
                    minute: "2-digit",
                    timeZone: "Asia/Taipei",
                  }).format(new Date(m.scheduled_time));
                  const court = getCourtDisplay(m);
                  const p1 = m.player1?.name || "TBD";
                  const p2 = m.player2?.name || "TBD";
                  return (
                    <tr key={m.id} className="hover:bg-yellow-50 transition-colors">
                      <td className="px-4 py-3 whitespace-nowrap text-sm font-medium text-gray-700">{timeStr}</td>
                      <td className="px-4 py-3 whitespace-nowrap text-sm text-gray-700">{court}</td>
                      <td className="px-4 py-3 whitespace-nowrap text-sm text-gray-800">
                        <span className="font-semibold">{p1}</span>
                        <Link 
                          href={`/sports/${singleEvent?.sport?.toLowerCase() || 'tennis'}/matches/${m.id}`}
                          className="mx-3 text-lg font-bold text-ntu-green hover:text-green-700 hover:underline cursor-pointer transition-colors"
                        >
                          {t('sports.vs')}
                        </Link>
                        <span className="font-semibold">{p2}</span>
                      </td>
                      <td className="px-4 py-3 whitespace-nowrap text-sm text-center">
                        {m.status === "completed" ? (
                          <span className="inline-block px-3 py-1 text-xs font-semibold text-green-800 bg-green-100 rounded-full">{t('sports.completed')}</span>
                        ) : m.status === "live" ? (
                          <span className="inline-block px-3 py-1 text-xs font-semibold text-red-800 bg-red-100 rounded-full animate-pulse">{t('sports.live')}</span>
                        ) : m.status === "delayed" ? (
                          <span className="inline-block px-3 py-1 text-xs font-semibold text-amber-700 bg-amber-100 rounded-full">{t('sports.delayed')}</span>
                        ) : (
                          <span className="inline-block px-3 py-1 text-xs font-semibold text-gray-700 bg-gray-100 rounded-full">{t('sports.upcoming')}</span>
                        )}
                      </td>
                    </tr>
                  );
                })}
              </tbody>
            </table>
          </div>
          
          {/* Mobile Card View */}
          <div className="md:hidden space-y-3">
            {matchesToShow.map((m: any) => {
              const timeStr = new Intl.DateTimeFormat(locale === 'zh' ? "zh-TW" : "en-US", {
                hour: "2-digit",
                minute: "2-digit",
                timeZone: "Asia/Taipei",
              }).format(new Date(m.scheduled_time));
              const court = getCourtDisplay(m);
              const p1 = m.player1?.name || "TBD";
              const p2 = m.player2?.name || "TBD";
              return (
                <div key={m.id} className="bg-white rounded-lg p-4 shadow-sm border border-yellow-200">
                  <div className="flex items-center justify-between mb-2">
                    <span className="text-sm font-semibold text-gray-700">{timeStr}</span>
                    {m.status === "completed" ? (
                      <span className="px-2 py-1 text-xs font-semibold text-green-800 bg-green-100 rounded-full">{t('sports.completed')}</span>
                    ) : m.status === "live" ? (
                      <span className="px-2 py-1 text-xs font-semibold text-red-800 bg-red-100 rounded-full animate-pulse">{t('sports.live')}</span>
                    ) : m.status === "delayed" ? (
                      <span className="px-2 py-1 text-xs font-semibold text-amber-700 bg-amber-100 rounded-full">{t('sports.delayed')}</span>
                    ) : (
                      <span className="px-2 py-1 text-xs font-semibold text-gray-700 bg-gray-100 rounded-full">{t('sports.upcoming')}</span>
                    )}
                  </div>
                  <div className="text-sm text-gray-600 mb-2">{t('sports.courtLabel')}{court}</div>
                  <div className="text-sm text-gray-800">
                    <span className="font-semibold">{p1}</span>
                    <Link 
                      href={`/sports/${singleEvent?.sport?.toLowerCase() || 'tennis'}/matches/${m.id}`}
                      className="mx-3 text-lg font-bold text-ntu-green hover:text-green-700 hover:underline cursor-pointer transition-colors"
                    >
                      {t('sports.vs')}
                    </Link>
                    <span className="font-semibold">{p2}</span>
                  </div>
                </div>
              );
            })}
          </div>
        </div>
      )}

      {matchesToShow.length === 0 && (
        <div className="bg-gradient-to-r from-yellow-50 to-amber-50 border-l-4 border-yellow-400 p-4 sm:p-6 mb-6 sm:mb-8 rounded-xl shadow-md animate-scaleIn">
          <div className="flex flex-col sm:flex-row sm:items-start sm:justify-between mb-3 sm:mb-4 gap-2">
            <h2 className="text-base sm:text-lg font-semibold text-yellow-800">{title}</h2>
            <span className="text-xs sm:text-sm text-yellow-700">{t('sports.autoGenerated')}</span>
          </div>
          <p className="text-yellow-800 text-sm sm:text-base">{emptyMessage}</p>
        </div>
      )}

      {/* Latest Announcement */}
      {latestAnnouncement && (
        <div className="bg-white rounded-xl shadow-md p-5 sm:p-6 mb-6 sm:mb-8 border border-gray-100 animate-scaleIn">
          <div className="flex items-start justify-between mb-3">
            <h2 className="text-xl font-semibold text-ntu-green">{t('announcements.title')}</h2>
            <Link href="/sports/tennis/announcements" className="text-ntu-green hover:underline text-xs sm:text-sm">
              {t('announcements.viewAll')} →
            </Link>
          </div>
          <p className="text-xs sm:text-sm text-gray-500 mb-2">
            {new Date(latestAnnouncement.created_at).toLocaleString(locale === 'zh' ? 'zh-TW' : 'en-US')}
          </p>
          <h3 className="text-lg font-semibold text-gray-800 mb-2">{latestAnnouncement.title}</h3>
          <div className="text-sm sm:text-base text-gray-700 line-clamp-3">
            <MarkdownText content={latestAnnouncement.content} />
          </div>
        </div>
      )}
    </>
  );
}

