export type Locale = 'zh' | 'en';

export const locales: Locale[] = ['zh', 'en'];
export const defaultLocale: Locale = 'zh';

export const translations = {
  zh: {
    // Navigation
    nav: {
      home: '首頁',
      share: '分享',
      qrCode: 'QR Code',
      menu: '選單',
    },
    // Homepage
    home: {
      title: 'NTU Sports',
      subtitle: '台大運動賽事管理平台 - 即時賽程、戰績、公告一手掌握',
      description: '支援多種運動項目，提供完整的賽事資訊與即時更新',
      sports: '運動項目',
      sportsDescription: '點擊下方運動項目查看最新賽事資訊',
      viewDetails: '立即查看',
      viewDraw: '查看籤表、賽程、戰績與最新公告',
    },
    // Sports Page
    sports: {
      selectEvent: '選擇一個賽事查看詳情',
      tournamentOverview: '賽事概覽',
      eventDescription: '賽事說明',
      dates: '日期',
      venue: '地點',
      description: '說明',
      timeUntilStart: '距離賽事開始',
      todaySchedule: '今日賽程',
      tomorrowSchedule: '明日賽程預告',
      noMatchesToday: '今日沒有已排定的比賽。',
      noMatchesTomorrow: '明日沒有已排定的比賽。',
      autoGenerated: '依照目前排定之賽程時間產生',
      time: '時間',
      court: '場地',
      matchup: '對戰組合',
      status: '狀態',
      completed: '已完成',
      live: '進行中',
      delayed: '延遲',
      upcoming: '即將開始',
      viewEvent: '查看賽事',
      tennisEvents: 'NTU Tennis Events',
      courtLabel: '場地：',
      vs: 'vs',
    },
    // Footer
    footer: {
      about: '關於 NTU Sports',
      aboutText: '台大運動賽事管理平台，提供即時賽程、戰績、籤表與公告服務',
      quickLinks: '快速連結',
      features: '功能特色',
      feature1: '即時賽程更新',
      feature2: '完整戰績統計',
      feature3: '自動化公告系統',
      feature4: '多運動支援',
      sportsSupported: '支援多種運動：網球、籃球、足球、排球等',
      copyright: '台灣大學運動賽事管理平台. All rights reserved.',
      madeWith: 'Made with ❤️ for NTU Sports Community',
    },
    // Share
    share: {
      shareToFacebook: '分享到 Facebook',
      shareToLine: '分享到 Line',
      shareToTwitter: '分享到 Twitter',
      copyLink: '複製連結',
      linkCopied: '連結已複製到剪貼簿！',
      copyFailed: '複製失敗，請手動複製',
      qrCodeTitle: '掃描 QR Code 分享此賽事',
      close: '關閉',
    },
  },
  en: {
    // Navigation
    nav: {
      home: 'Home',
      share: 'Share',
      qrCode: 'QR Code',
      menu: 'Menu',
    },
    // Homepage
    home: {
      title: 'NTU Sports',
      subtitle: 'NTU Sports Management Platform - Real-time schedules, results, and announcements',
      description: 'Supporting multiple sports with complete event information and real-time updates',
      sports: 'Sports',
      sportsDescription: 'Click on a sport below to view the latest event information',
      viewDetails: 'View Now',
      viewDraw: 'View draws, schedules, results, and latest announcements',
    },
    // Sports Page
    sports: {
      selectEvent: 'Select an event to view details',
      tournamentOverview: 'Tournament Overview',
      eventDescription: 'Event Description',
      dates: 'Dates',
      venue: 'Venue',
      description: 'Description',
      timeUntilStart: 'Time Until Tournament Starts',
      todaySchedule: "Today's Schedule",
      tomorrowSchedule: "Tomorrow's Schedule",
      noMatchesToday: 'No scheduled matches today.',
      noMatchesTomorrow: 'No scheduled matches tomorrow.',
      autoGenerated: 'Auto-generated based on scheduled match times',
      time: 'Time',
      court: 'Court',
      matchup: 'Matchup',
      status: 'Status',
      completed: 'Completed',
      live: 'Live',
      delayed: 'Delayed',
      upcoming: 'Upcoming',
      viewEvent: 'View Event',
      tennisEvents: 'NTU Tennis Events',
      courtLabel: 'Court:',
      vs: 'vs',
    },
    // Footer
    footer: {
      about: 'About NTU Sports',
      aboutText: 'NTU Sports Management Platform providing real-time schedules, results, draws, and announcements',
      quickLinks: 'Quick Links',
      features: 'Features',
      feature1: 'Real-time Schedule Updates',
      feature2: 'Complete Statistics',
      feature3: 'Automated Announcement System',
      feature4: 'Multi-Sport Support',
      sportsSupported: 'Supporting multiple sports: Tennis, Basketball, Soccer, Volleyball, etc.',
      copyright: 'National Taiwan University Sports Platform. All rights reserved.',
      madeWith: 'Made with ❤️ for NTU Sports Community',
    },
    // Share
    share: {
      shareToFacebook: 'Share to Facebook',
      shareToLine: 'Share to Line',
      shareToTwitter: 'Share to Twitter',
      copyLink: 'Copy Link',
      linkCopied: 'Link copied to clipboard!',
      copyFailed: 'Copy failed, please copy manually',
      qrCodeTitle: 'Scan QR Code to share this event',
      close: 'Close',
    },
  },
} as const;

export type TranslationKey = keyof typeof translations.zh;

